import Link from 'next/link'
import { ArrowLeft, BookOpenCheck, CheckCircle2, CircleAlert, FileText } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'

const delivered = ['Web pública responsive y captación', 'Tecnificación, Campus y Torneos', 'Portal Familias con jugadores, pagos, documentos, comunicaciones y videoteca', 'CRM de jugadores, tutores, trabajadores y solicitudes', 'Calendario, equipos, finanzas, roles y ajustes', 'Inscripción pública con revisión previa', 'Muro Academy privado y moderable']
const pending = ['Validar precio definitivo: el documento indica 80 €/150 €, mientras el dossier y la web actual muestran 75 €/140 €.', 'Configurar Stripe antes de cobrar online.', 'Configurar Resend o SMTP propio para correos transaccionales.', 'Publicar Campus, Torneos y productos reales cuando estén definidos.', 'Completar integración de WhatsApp, Analytics y Meta Pixel con las cuentas del cliente.', 'Definir y comunicar las normas de uso y consentimiento de imagen de menores antes de abrir el Muro Academy.']

export default function BusinessBriefPage() {
    return <div className="mx-auto max-w-5xl space-y-6 pb-12"><Link href="/admin/ajustes"><Button variant="ghost" className="-ml-3 text-slate-600"><ArrowLeft className="mr-2 h-4 w-4" />Volver a Ajustes</Button></Link><header className="rounded-3xl bg-navy p-7 text-white shadow-xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-gold">Documento base del negocio · v1</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-black"><BookOpenCheck className="h-8 w-8 text-gold" />Academy Costa Brava</h1><p className="mt-3 max-w-3xl text-slate-300">Passió · Formació · Evolució. El fútbol como herramienta de aprendizaje para la vida.</p></header>
        <div className="grid gap-5 md:grid-cols-2"><Card><CardHeader><CardTitle>Propósito</CardTitle><CardDescription>Presentación pública profesional y ecosistema privado de gestión y comunicación con familias.</CardDescription></CardHeader><CardContent className="space-y-3 text-sm text-slate-700"><p><strong>Oferta:</strong> tecnificación de temporada, campus vacacionales y torneos/experiencias.</p><p><strong>Portal:</strong> cada familia gestiona varios jugadores desde una sola cuenta.</p><p><strong>Administración:</strong> Academy gestiona personas, actividades, contenidos, pagos, comunicaciones y permisos.</p></CardContent></Card><Card><CardHeader><CardTitle>Filosofía y valores</CardTitle><CardDescription>Formación complementaria al club de procedencia.</CardDescription></CardHeader><CardContent className="text-sm text-slate-700"><p>Desarrollo técnico, táctico/cognitivo, físico/coordinativo y socioafectivo.</p><p className="mt-3 font-semibold">Esfuerzo · Respeto · Disciplina · Compañerismo · Confianza · Responsabilidad · Superación</p></CardContent></Card></div>
        <Card><CardHeader><CardTitle className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-emerald-600" />Ya cubierto por la plataforma</CardTitle></CardHeader><CardContent><ul className="grid gap-3 text-sm md:grid-cols-2">{delivered.map((item) => <li key={item} className="rounded-lg bg-emerald-50 p-3 text-emerald-950">{item}</li>)}</ul></CardContent></Card>
        <Card className="border-amber-200"><CardHeader><CardTitle className="flex items-center gap-2"><CircleAlert className="h-5 w-5 text-amber-600" />Pendiente de decisión o contenido del cliente</CardTitle><CardDescription>Estas tareas requieren datos, cuentas o validación comercial de Academy.</CardDescription></CardHeader><CardContent><ul className="space-y-3 text-sm">{pending.map((item) => <li key={item} className="rounded-lg bg-amber-50 p-3 text-amber-950">{item}</li>)}</ul></CardContent></Card>
        <Card><CardHeader><CardTitle className="flex items-center gap-2"><FileText className="h-5 w-5 text-navy" />Requisitos funcionales acordados</CardTitle></CardHeader><CardContent className="grid gap-4 text-sm text-slate-700 md:grid-cols-2"><p><strong>Web pública:</strong> inicio, metodología, logros, tecnificación, campus, torneos, contacto, inscripciones y diseño prioritario para móvil.</p><p><strong>Portal:</strong> perfil del jugador, actividades, evaluaciones, documentos, pagos, comunicados, logros, videoteca y Muro Academy.</p><p><strong>Muro:</strong> publicaciones privadas o para comunidad, directas dentro del portal y nunca expuestas en Internet. Academy puede retirarlas.</p><p><strong>Operativa:</strong> precios, horarios, plazas y actividades deben gestionarse desde administración sin depender del programador.</p></CardContent></Card>
    </div>
}
